### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by Kelvin-Ben** [OscarFMdev/reactCalculator#5]
## Math Magicians
- Hey @OscarFMdev, excellent job on the project; you did a great job with the component implementation.
- I note that you've also added hooks to your refactored classes, which is a smart idea. The project's design is particularly incredible because you used a CSS grid, which I initially didn't think would be a good idea.
### Congrats and Happy coding.

**Comment by OscarFMdev** [comment]
Thanks @Kelvin-Ben 🙌
